sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
#- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- curl -L -o installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/racket-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- raco pkg install --auto -i --no-setup --skip-installed gui-test
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg update -i --auto --no-setup gui-lib/ gui-doc/ gui/ tex-table/ gui-test/
- raco setup --pkgs gui gui-lib gui-test tex-table
#- raco pkg install --auto compiler-lib
- ls $HOME/.racket/download-cache
- ls

script:
- racket -l tests/gracket/wxme

after_script:
