sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

services:
- xvfb

before_install:
#- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- curl -L -o installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/racket-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- raco pkg install --auto -i --no-setup --skip-installed gui-test
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg update -i --auto --no-setup gui-lib/ gui-doc/ gui/ tex-table/ gui-test/
- raco setup --pkgs gui gui-lib gui-test tex-table
- ls $HOME/.racket/download-cache

script:
- racket -l tests/gracket/wxme
- raco test -e -l tests/gracket/test

after_script:
